### ISSUE TITLE
Should EasyTab handle context changes?

### ISSUE THREAD

**Issue by serge-rgb** [ApoorvaJ/EasyTab#15]
Changing Wacom settings, like the wacom input area or screen area, when the EasyTab client app is open requires the client to handle it.

Changing display settings (like turning off one display) also requires the client to handle it, since the Wacom context needs to be rebuilt.

In my case, I am currently not handling it. My app needs a restart whenever those two particular cases happen. Not a huge deal, but the other applications I test seem to handle these cases without problems.

I was debating whether to open this issue or not, since this is one of those "Drop the Easy from EasyTab" issues. 

The applications I mentioned that handle these cases seem to work _when the wacom driver crashes_, so I have to assume that they are using the Windows Stylus API. Also, the Wacom sample code is not helpful at all for cases like these.

So I'm thinking that one way forward should be to support the Stylus API and leave the Wacom layer as a fallback for when the Stylus API is not available or when EasyTab is compiled as C99.

This could add a lot of complexity to the code, so it might be a bad idea? I just wanted to write my thoughts somewhere that wasn't email, since this is an open source project. I'm curious to read your thoughts, but feel free to close the issue, since there is no code to show yet :)

**Comment by ApoorvaJ** [comment]
**Settings change**
I think switching to the Microsoft Stylus API will incur problems of its own, such as C99 compatibility. I'd vote to keep that out of EasyTab at least for now, until we find a more compelling reason to add it.

Can we auto-detect driver settings change somehow? If yes, we could add internal lazy reloading to the library to refresh the context.

If this adds too much code complexity, we might want to simply not add this functionality in here. Can we get in touch with someone who has written the apps that do The Right Thing™? There may be an undocumented way to get refreshed settings from the driver.

**Driver crash**
I'm okay with having to restart the application in case this happens, as long as we don't segfault in EasyTab. If we do decide to go the lazy reloading route for the settings refresh, this may get solved too. If not, I can live with it.

**Comment by GrayHatter** [comment]
@ApoorvaJ an email to wacom would be very likely to return something helpful.

**Comment by serge-rgb** [comment]
Good to hear your thoughts and know where you stand. 

I don't know of a way to detect driver setting changes.  It will be useful to go looking into GTK and Qt and see what they are doing.

I mentioned the driver crash because on one occasion, my Wacom driver crashed without recovery. EasyTab didn't work because Wacom was FUBAR, yet Mischief and Krita(IIRC) had tablet support.

I'm closing the issue for now :)

**Comment by serge-rgb** [comment]
Sorry to nag, but I had to correct myself. I must be remembering incorrectly as to what happened when the driver crashed. I attached a debugger to Krita and Mischief, and they are both calling WTPacketsPeek and WTPacketsGet respectively, so they are using the Wacom API, not the Windows API as I was assuming.
