### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by Muvkina** [ApoorvaJ/EasyTab#19]
I would like to use this library however I do not feel comfortable using it until it has a license. Well I would like to believe the author means his claim of public domain it cannot hold up in every country and furthermore the author could turn around and sue for copyright. So I would like to propose adding a license of some sort. If you would like to keep it basically public domain I would recommend https://creativecommons.org/choose/zero/ as a license. It basically is public domain however covers more countries and ensures developer safety. At the end of the day it is your choice obviously but I would like to propose this.

**Comment by ApoorvaJ** [comment]
Done.
