### ISSUE TITLE
Add includes? Define allocator macro?

### ISSUE THREAD

**Issue by serge-rgb** [ApoorvaJ/EasyTab#7]
I had a problem compiling EasyTab as a standalone lib (vs2015). It doesn't find calloc or strstr. On windows this is fixed by including `#include <stdlib.h>` and `#include <string.h>`.

IMO, the library should include what it needs, although in practice I am guessing that it will only ever be included into codebases that already have calloc and strstr included.

Related: Maybe instead of directly using calloc and free, there should be a `EASYTAB_CALLOC` and `EASYTAB_FREE` to give the client control over the allocation scheme.

**Comment by ApoorvaJ** [comment]
I have already [included stdint.h](https://github.com/ApoorvaJ/EasyTab/blob/master/easytab.h#L159) directly in easytab.h. How do you feel about including stdlib and string right there? Both are present on Windows and Linux, and will prevent additional calloc/free macro complexity.

**Comment by serge-rgb** [comment]
Yeah, I think the library should include what it needs :)

**Comment by ApoorvaJ** [comment]
Calloc/free macros not added, to keep things simple. Their usage frequency within EasyTab is very low, and advanced users can just change the source code.
